services:
  - type: web
    name: image-gallery-ctf
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --workers 2 --timeout 120"
    envVars:
      - key: SECRET_KEY
        value: "change_this_in_production"
